name: Build and Publish WPF Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x  # 使用 .NET 6 SDK

      # 恢复依赖项
      - name: Restore dependencies
        run: dotnet restore NewcoreTestTool.sln

      # 构建项目
      - name: Build the project
        run: dotnet build NewcoreTestTool.sln --configuration Release --no-restore

      # 发布应用
      - name: Publish application
        run: dotnet publish NewcoreTestTool/NewcoreTestTool.csproj --configuration Release --output ./output

      # 压缩发布文件
      - name: Create zip file
        run: Compress-Archive -Path ./output/* -DestinationPath ./output/NewcoreTestTool.zip

      # 上传发布文件到 GitHub Actions 工作区
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: WPF-Application
          path: ./output/NewcoreTestTool.zip
